### ISSUE TITLE
Is there an equivalent to veritas distribution?

### ISSUE THREAD

**Issue by scottschulthess** [cloudfoundry/cfdot#3]
Just curious, I liked that output format

**Comment by emalm** [comment]
Hi, @scottschulthess,

We haven't introduced a deployment-wide aggregation command like `veritas distribution` yet, but I'd eventually like to add something that would be valuable in the same way without necessarily having the exact same output. Would you be able to share some examples of how you currently use `veritas distribution` to interact with a Diego deployment, and why? I'm more than happy to chat with you on the CF Slack about this too, either in the #diego channel or via DM.

Thanks,
Eric, CF Diego PM

**Comment by scottschulthess** [comment]
Hey Eric, sorry missed this response.  Yep its just a nice visualization to use to see why the cells are taking a long time to drain and where they are at.  Not critical

**Comment by scottschulthess** [comment]
closing issue as it's more of a nice to have

**Comment by emalm** [comment]
Hey, @scottschulthess, I'm wondering whether some light `jq` processing of either the `cfdot actual-lrp-groups` or the more recently added `cfdot cell-states` output would be helpful in cases when you're monitoring evacuating cells, their instances, and the replacements. Are you interested primarily in tracking which cells are still evacuating and how many LRP and Task instances they still have, or other metrics?

I was playing around with processing some of this output, and I could see the following reports being useful in various cases:

Count of remaining LRP instances and Tasks on each evacuating cell, sorted by decreasing LRP instance count:

```
# cfdot cell-states | jq 'select(.Evacuating) | "\(.cell_id): L \(.LRPs | length), T \(.Tasks | length)"' -r | sort -nr -k3
87f91a7a-69aa-4c7f-8c75-c4720d12d158: L 4 T 1
c56525a2-8728-4955-a5bb-e8ff213182f1: L 2 T 1
```

List of remaining LRPs and Tasks on each evacuating cell:

```
# cfdot cell-states | jq 'select(.Evacuating) | .cell_id as $c | (.LRPs[] | "\($c): L \(.process_guid) \(.index) \(.instance_guid)"), (.Tasks[] | "\($c): T \(.TaskGuid)")' -r | sort
87f91a7a-69aa-4c7f-8c75-c4720d12d158: L 0acb81d9-8b29-4f31-9194-73f29cff9ce7-08f32197-ecb0-4041-ac47-199549ff0e1e 1 3d807fee-cb0f-4b0f-7c13-4233
87f91a7a-69aa-4c7f-8c75-c4720d12d158: L e5e7653f-3cfc-49a9-8903-17b6324728f9-d4b9368e-53c1-4f2e-b1aa-b76e01de103d 0 aea0eaf8-bc02-4291-4c95-5fcf
87f91a7a-69aa-4c7f-8c75-c4720d12d158: L e5e7653f-3cfc-49a9-8903-17b6324728f9-d4b9368e-53c1-4f2e-b1aa-b76e01de103d 1 04444e27-2f7c-4667-5b30-3f4e
87f91a7a-69aa-4c7f-8c75-c4720d12d158: L e5e7653f-3cfc-49a9-8903-17b6324728f9-d4b9368e-53c1-4f2e-b1aa-b76e01de103d 2 e1f4135f-e92e-40d8-6fc3-8fa5
87f91a7a-69aa-4c7f-8c75-c4720d12d158: T 27e6c826-d872-45e3-b7fd-468dd65c11bf
c56525a2-8728-4955-a5bb-e8ff213182f1: L 0acb81d9-8b29-4f31-9194-73f29cff9ce7-08f32197-ecb0-4041-ac47-199549ff0e1e 0 393321c0-2672-4afb-7d1b-90f8
c56525a2-8728-4955-a5bb-e8ff213182f1: L 0acb81d9-8b29-4f31-9194-73f29cff9ce7-08f32197-ecb0-4041-ac47-199549ff0e1e 2 23c2fffd-d706-4b87-7ab4-496b
c56525a2-8728-4955-a5bb-e8ff213182f1: T 4393fc88-f43b-4c09-ab61-35f05a7b011d
```

Mapping from evacuating LRP instances to their replacements on other cells:

```
# cfdot actual-lrp-groups | jq 'select(.evacuating != null) | "\(.evacuating.cell_id): \(.evacuating.process_guid)/\(.evacuating.index) -> \(.instance.cell_id) \(.instance.state) \((now - (.instance.since / 1000000000)) | floor)s"' -r | sort
87f91a7a-69aa-4c7f-8c75-c4720d12d158: 0acb81d9-8b29-4f31-9194-73f29cff9ce7-08f32197-ecb0-4041-ac47-199549ff0e1e/1 -> 8943cd9c-60b4-4cef-a43e-aacebedf06c2 CLAIMED 32s
87f91a7a-69aa-4c7f-8c75-c4720d12d158: e5e7653f-3cfc-49a9-8903-17b6324728f9-d4b9368e-53c1-4f2e-b1aa-b76e01de103d/0 -> 8943cd9c-60b4-4cef-a43e-aacebedf06c2 CLAIMED 32s
87f91a7a-69aa-4c7f-8c75-c4720d12d158: e5e7653f-3cfc-49a9-8903-17b6324728f9-d4b9368e-53c1-4f2e-b1aa-b76e01de103d/1 -> da783e46-1d5b-4049-b735-a031bf305592 CLAIMED 33s
87f91a7a-69aa-4c7f-8c75-c4720d12d158: e5e7653f-3cfc-49a9-8903-17b6324728f9-d4b9368e-53c1-4f2e-b1aa-b76e01de103d/2 -> da783e46-1d5b-4049-b735-a031bf305592 CLAIMED 31s
c56525a2-8728-4955-a5bb-e8ff213182f1: 0acb81d9-8b29-4f31-9194-73f29cff9ce7-08f32197-ecb0-4041-ac47-199549ff0e1e/0 -> da783e46-1d5b-4049-b735-a031bf305592 CLAIMED 21s
c56525a2-8728-4955-a5bb-e8ff213182f1: 0acb81d9-8b29-4f31-9194-73f29cff9ce7-08f32197-ecb0-4041-ac47-199549ff0e1e/2 -> 8943cd9c-60b4-4cef-a43e-aacebedf06c2 CLAIMED 21s
```

(Also, great to meet you in person at Summit last month!)

Best,
Eric

**Comment by scottschulthess** [comment]
Sorry I missed this Eric

Yes the use case is it's nice to see something is happening as we're waiting sometimes extremely long times to drain (because of apps taking a while to evac & boot up on new cells)

That is some fancy JQing, i will .  It was nice to meet you as well thanks!
